import {test,expect} from '@playwright/test';
const base=process.env.PREVIEW_URL||'http://127.0.0.1:3000';
let auth,bookId;const title='Buku Uji Browser '+Date.now();const code='UJI-'+Date.now();
const headers={'Origin':new URL(base).origin,'X-Sinabos-Request':'1','Content-Type':'application/json'};
test.describe.configure({mode:'serial'});
test.beforeAll(async({browser})=>{const context=await browser.newContext({baseURL:base});const page=await context.newPage();await page.goto('/');await page.locator('#username').fill('admin');await page.locator('#password').fill('Demo-Admin-2026!');await page.getByRole('button',{name:/^Masuk/}).click();await expect(page.getByRole('heading',{name:'Ringkasan Buku'})).toBeVisible();await expect(page.locator('.stat-number')).toHaveCount(4);auth=await context.storageState();await context.close();});
async function adminPage(browser){const c=await browser.newContext({baseURL:base,storageState:auth,viewport:{width:1440,height:1000}});const p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('/');await expect(p.getByRole('heading',{name:'Ringkasan Buku'})).toBeVisible();return {c,p,errors};}
test('dashboard, navigasi admin, cookie aman, aset tambahan tidak dimuat awal',async({browser})=>{const {c,p,errors}=await adminPage(browser);await expect(p.locator('.stat-number')).toHaveCount(4);const initial=await p.evaluate(()=>performance.getEntriesByType('resource').map(x=>x.name));expect(initial.filter(x=>x.includes('chunk-')&&!x.includes('chunk-UJVVLSSD'))).toHaveLength(0);expect(await p.evaluate(()=>document.cookie)).not.toContain('sinabos');const cookies=await c.cookies();expect(cookies.find(x=>x.name==='__Host-sinabos').httpOnly).toBe(true);expect(cookies.find(x=>x.name==='__Host-sinabos').secure).toBe(true);await p.screenshot({path:'artifacts/dashboard-desktop.png',fullPage:true});for(const v of ['books','history','active','rombel','users','report','audit','settings']){await p.locator(`[data-view="${v}"]`).click();await expect(p.locator('#page h1')).toBeVisible();if(v!=='settings')await expect(p.locator('#view-data')).not.toContainText('Data belum berhasil dimuat');}expect(errors).toEqual([]);await c.close();});
test('tambah buku langsung tersedia 50; edit master tanpa field penimpa total',async({browser})=>{const {c,p,errors}=await adminPage(browser);await p.locator('[data-view="books"]').click();await p.getByRole('button',{name:'Tambah buku'}).click();for(const [field,value] of Object.entries({kode_buku:code,judul:title,mata_pelajaran:'Matematika',penulis:'Tim Uji',penerbit:'Penerbit Uji',total_awal:'50'}))await p.locator('#f-'+field).fill(value);await p.getByRole('button',{name:'Simpan buku & stok awal'}).click();await expect(p.locator('#modal')).not.toBeVisible();await p.locator('#search').fill(code);const row=p.locator('tbody tr').filter({hasText:code});await expect(row).toBeVisible();await expect(row.locator('.inventory-number')).toHaveText('50');await row.getByRole('button',{name:'Edit',exact:true}).click();await expect(p.locator('#f-total_awal')).toHaveCount(0);await p.getByRole('button',{name:'Simpan perubahan'}).click();await expect(p.locator('#modal')).not.toBeVisible();await expect(row.locator('.inventory-number')).toHaveText('50');expect(errors).toEqual([]);await c.close();});
test('pinjam lalu kembali kondisi campuran: stok 44; bukti tidak hilang otomatis',async({browser})=>{const {c,p,errors}=await adminPage(browser);await p.locator('[data-view="operasional"]').click();await p.locator('#barcode-input').fill('RBL-VII-A');await p.getByRole('button',{name:/Buka form/i}).click();await expect(p.locator('#item-book-0')).toBeVisible();bookId=await p.locator('#item-book-0 option').filter({hasText:title}).getAttribute('value');await p.locator('#item-book-0').selectOption(bookId);await p.locator('#item-qty-0').fill('10');await p.getByRole('button',{name:'Simpan transaksi'}).click();await expect(p.locator('#receipt-host')).toContainText('Transaksi tersimpan');await p.waitForTimeout(1600);await expect(p.locator('#receipt-host .receipt-code')).toBeVisible();await p.getByRole('button',{name:'Transaksi baru'}).click();await p.locator('#barcode-input').fill('RBL-VII-A');await p.getByRole('button',{name:/Buka form/i}).click();await p.locator('#tx-kind').selectOption('kembali');for(let i=0;i<3;i++){if(i)await p.getByRole('button',{name:'Tambah baris'}).click();await p.locator('#item-book-'+i).selectOption(bookId);await p.locator('#item-qty-'+i).fill(String([4,2,1][i]));await p.locator('#item-condition-'+i).selectOption(['baik','rusak','hilang'][i]);}await p.getByRole('button',{name:'Simpan transaksi'}).click();await expect(p.locator('#receipt-host')).toContainText('Transaksi tersimpan');await p.screenshot({path:'artifacts/receipt-desktop.png',fullPage:true});await p.locator('[data-view="books"]').click();await p.locator('#search').fill(code);const row=p.locator('tbody tr').filter({hasText:code});await expect(row.locator('.inventory-number')).toHaveText('44');await expect(row).toContainText('Rusak 2');await expect(row).toContainText('Hilang 1');expect(errors).toEqual([]);await c.close();});
test('respons simpan hilang setelah commit: reload dan periksa status tidak menggandakan',async({browser})=>{const {c,p,errors}=await adminPage(browser);await p.locator('[data-view="operasional"]').click();await p.locator('#barcode-input').fill('RBL-VII-A');await p.getByRole('button',{name:/Buka form/i}).click();await p.locator('#item-book-0').selectOption(bookId);await p.locator('#item-qty-0').fill('1');let dropped=false;await p.route('**/api',async route=>{const payload=route.request().postDataJSON();if(payload.action==='circulate'&&!dropped){dropped=true;await route.fetch();await route.abort('connectionfailed');}else await route.continue();});await p.getByRole('button',{name:'Simpan transaksi'}).click();await expect(p.locator('#pending')).toBeVisible();await p.reload();await expect(p.locator('#pending')).toBeVisible();await p.getByRole('button',{name:'Periksa status',exact:true}).click();await expect(p.locator('#pending')).not.toBeVisible();await expect(p.locator('#receipt-host')).toContainText('Transaksi tersimpan');await p.locator('[data-view="books"]').click();await p.locator('#search').fill(code);await expect(p.locator('tbody tr').filter({hasText:code}).locator('.inventory-number')).toHaveText('43');expect(errors).toEqual([]);await c.close();});
test('QR dibuat lazy dan laporan dapat diunduh tanpa API eksternal',async({browser})=>{const {c,p,errors}=await adminPage(browser);await p.locator('[data-view="rombel"]').click();await p.getByRole('button',{name:'Label QR'}).first().click();await expect(p.locator('.qr-label svg')).toBeVisible();await p.getByRole('button',{name:'Tutup',exact:true}).click();await p.locator('[data-view="report"]').click();await expect(p.locator('tbody tr').first()).toBeVisible();const download=p.waitForEvent('download');await p.getByRole('button',{name:'Unduh CSV'}).click();expect((await download).suggestedFilename()).toMatch(/^Sinabos-mutasi-\d{4}-\d{2}\.csv$/);expect(errors).toEqual([]);await c.close();});
test('akun guru mobile tidak memiliki akses admin; layout tidak melebar',async({browser})=>{const c=await browser.newContext({baseURL:base,viewport:{width:390,height:844},isMobile:true,hasTouch:true});const p=await c.newPage();await p.goto('/');await p.screenshot({path:'artifacts/login-mobile.png',fullPage:true});await p.locator('#username').fill('guru.demo');await p.locator('#password').fill('Demo-Guru-2026!');await p.getByRole('button',{name:/^Masuk/}).click();await expect(p.getByRole('heading',{name:'Transaksi Rombel'})).toBeVisible();expect(await p.locator('[data-view="users"]').count()).toBe(0);const status=await p.evaluate(async()=>{const r=await fetch('/api',{method:'POST',headers:{'Content-Type':'application/json','X-Sinabos-Request':'1'},body:JSON.stringify({action:'books',data:{}})});return r.status;});expect(status).toBe(403);await p.locator('#barcode-input').fill('RBL-VII-A');await p.getByRole('button',{name:/Buka form/i}).click();await expect(p.locator('#tx-name')).toHaveValue('Guru Simulasi');expect(await p.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await p.screenshot({path:'artifacts/teacher-mobile.png',fullPage:true});await c.close();});
test('guru baru wajib mengganti password sebelum scan',async({browser})=>{const adminContext=await browser.newContext({baseURL:base,storageState:auth});const uname='guru.new.'+Date.now();const adminP=await adminContext.newPage();await adminP.goto('/');await expect(adminP.getByRole('heading',{name:'Ringkasan Buku'})).toBeVisible();const status=await adminP.evaluate(async username=>{const r=await fetch('/api',{method:'POST',headers:{'Content-Type':'application/json','X-Sinabos-Request':'1'},body:JSON.stringify({action:'saveUser',data:{username,full_name:'Guru Uji Baru',role:'guru',password:'First-Password-2026!',request_id:crypto.randomUUID()}})});return r.status;},uname);expect(status).toBe(200);await adminContext.close();const c=await browser.newContext({baseURL:base});const p=await c.newPage();await p.goto('/');await p.locator('#username').fill(uname);await p.locator('#password').fill('First-Password-2026!');await p.getByRole('button',{name:/^Masuk/}).click();await expect(p.getByRole('heading',{name:'Buat password pribadi Anda'})).toBeVisible();await p.locator('#f-old_password').fill('First-Password-2026!');await p.locator('#f-new_password').fill('Personal-Password-2026!');await p.locator('#f-confirm_password').fill('Personal-Password-2026!');await p.getByRole('button',{name:'Simpan password'}).click();await expect(p.locator('#modal')).not.toBeVisible();await expect(p.getByRole('heading',{name:'Transaksi Rombel'})).toBeVisible();await c.close();});

test('password request tertunda tidak tersimpan; reload dan retry memakai UUID sama',async({browser})=>{
 const {c,p,errors}=await adminPage(browser);const username='guru.retry.'+Date.now(),password='Retry-Secret-Browser-2026!';let originalId,retryId,dropped=false;
 await p.route('**/api',async route=>{const data=route.request().postDataJSON();if(data.action==='saveUser'&&data.data.username===username){if(!dropped){dropped=true;originalId=data.data.request_id;await route.abort('connectionfailed');return;}retryId=data.data.request_id;}await route.continue();});
 await p.locator('[data-view="users"]').click();await p.locator('[data-action="new-user"]').click();await p.locator('#f-username').fill(username);await p.locator('#f-full_name').fill('Guru Retry Browser');await p.locator('#f-password').fill(password);await p.getByRole('button',{name:'Buat akun',exact:true}).click();await expect(p.locator('#pending')).toBeVisible();
 const storage=await p.evaluate(()=>JSON.stringify(sessionStorage));expect(storage).not.toContain(password);expect(storage).toContain('needsPassword');
 await p.reload();await expect(p.locator('#pending')).toBeVisible();await p.getByRole('button',{name:'Ulangi permintaan yang sama'}).click();await p.locator('#retry-password').fill(password);await p.getByRole('button',{name:'Ulangi permintaan',exact:true}).click();await expect(p.locator('#pending')).not.toBeVisible();await expect(p.locator('#modal')).not.toBeVisible();expect(retryId).toBe(originalId);
 await p.locator('#search').fill(username);await expect(p.locator('tbody tr').filter({hasText:username})).toHaveCount(1);expect(errors).toEqual([]);await c.close();
});

test('CSP produksi mengizinkan dashboard dan QR tanpa inline script/style',async({browser})=>{
 const fs=await import('node:fs/promises');const headersText=await fs.readFile('public/_headers','utf8');const policy=headersText.match(/Content-Security-Policy: (.+)/)[1];
 const c=await browser.newContext({baseURL:base,storageState:auth});const p=await c.newPage();const violations=[];p.on('console',m=>{if(/content security policy|violates.*directive/i.test(m.text()))violations.push(m.text());});
 await p.route(base+'/',async route=>{const r=await route.fetch();await route.fulfill({response:r,headers:{...r.headers(),'content-security-policy':policy}});});
 await p.goto('/');await expect(p.locator('.stat-number')).toHaveCount(4);await p.locator('[data-view="rombel"]').click();await p.locator('[data-action="label"]').first().click();await expect(p.locator('.qr-label svg')).toBeVisible();await p.getByRole('button',{name:'Tutup',exact:true}).click();expect(violations).toEqual([]);await c.close();
});

test('QR gagal memuat memberi pesan; QR terlambat tidak menimpa modal baru',async({browser})=>{
 const fs=await import('node:fs/promises');const bundles=JSON.parse(await fs.readFile('artifacts/bundle-size.json','utf8'));const qr=bundles.files.find(x=>x.entry==='node_modules/qrcode/lib/browser.js').file.replace('public','');
 const first=await adminPage(browser);await first.p.route('**'+qr,r=>r.abort('connectionfailed'));await first.p.locator('[data-view="rombel"]').click();await first.p.locator('[data-action="label"]').first().click();await expect(first.p.getByRole('heading',{name:'Label belum dapat dibuat'})).toBeVisible();await first.c.close();
 const {c,p,errors}=await adminPage(browser);let release;const gate=new Promise(r=>release=r);await p.route('**'+qr,async r=>{await gate;await r.continue();});
 await p.locator('[data-view="rombel"]').click();await p.locator('[data-action="label"]').first().click();await expect(p.locator('#modal')).toBeVisible();await p.getByRole('button',{name:'Tutup',exact:true}).click();await p.locator('[data-action="new-rombel"]').click();release();
 await expect(p.locator('[data-action="label"]').first()).toBeEnabled();await expect(p.getByRole('heading',{name:'Tambah rombel'})).toBeVisible();await expect(p.locator('.qr-label')).toHaveCount(0);expect(errors).toEqual([]);await c.close();
});

test('kamera simulasi dihentikan saat ditutup; izin ditolak memberi fallback manual',async({browser})=>{
 const c=await browser.newContext({baseURL:base,storageState:auth});await c.addInitScript(()=>{
  window.BarcodeDetector=class{static async getSupportedFormats(){return ['qr_code'];}async detect(){return [];}};
  Object.defineProperty(navigator.mediaDevices,'getUserMedia',{value:async()=>{if(window.__denyCamera)throw new DOMException('Ditolak untuk pengujian','NotAllowedError');const canvas=document.createElement('canvas');canvas.width=320;canvas.height=240;canvas.getContext('2d').fillRect(0,0,320,240);window.__testStream=canvas.captureStream(1);return window.__testStream;}});
 });
 const p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('/');await p.locator('[data-view="operasional"]').click();await p.locator('[data-action="camera-open"]').click();await expect(p.locator('#camera-message')).toContainText('Kamera aktif.');await p.getByRole('button',{name:'Tutup kamera',exact:true}).click();expect(await p.evaluate(()=>window.__testStream.getTracks().every(t=>t.readyState==='ended'))).toBe(true);expect(await p.locator('#camera-video').evaluate(v=>v.srcObject)).toBe(null);
 await p.evaluate(()=>window.__denyCamera=true);await p.locator('[data-action="camera-open"]').click();await expect(p.locator('#camera-message')).toContainText('Izin kamera ditolak');await p.getByRole('button',{name:'Gunakan input manual',exact:true}).click();await expect(p.locator('#barcode-input')).toBeVisible();expect(errors).toEqual([]);await c.close();
});

test('logout membersihkan password/DOM; respons akun lama tidak masuk cache akun berikutnya',async({browser})=>{
 const {c,p,errors}=await adminPage(browser);let release,captured;const gate=new Promise(r=>release=r),ready=new Promise(r=>captured=r);let historyCalls=0;
 await p.route('**/api',async route=>{const data=route.request().postDataJSON();if(data.action==='history'){historyCalls++;if(historyCalls===1){const response=await route.fetch();captured();await gate;await route.fulfill({response});return;}}await route.continue();});
 await p.locator('[data-view="history"]').click();await ready;await p.locator('[data-view="settings"]').click();await p.locator('[data-action="change-password"]').click();await p.locator('#f-old_password').fill('Sensitive-DOM-Test-Only');
 // Synthetic click intentionally exercises cleanup even while a dialog is open.
 await p.evaluate(()=>document.querySelector('#password').type='text');
 await p.locator('[data-action="logout"]').evaluate(b=>b.click());await expect(p.locator('#login')).toBeVisible();await expect(p.locator('#password')).toHaveAttribute('type','password');await expect(p.locator('#profile-name')).toBeEmpty();await expect(p.locator('#modal-content')).toBeEmpty();await expect(p.locator('#page')).toBeEmpty();expect((await c.cookies()).some(x=>x.name==='__Host-sinabos')).toBe(false);
 await p.locator('#username').fill('guru.demo');await p.locator('#password').fill('Demo-Guru-2026!');await p.getByRole('button',{name:/^Masuk/}).click();await expect(p.locator('#profile-name')).toHaveText('Guru Simulasi');release();await p.locator('[data-view="history"]').click();await expect(p.locator('#view-data')).not.toContainText(title);await expect(p.locator('#view-data tbody tr')).toHaveCount(3);expect((await p.locator('#view-data tbody tr').allTextContents()).every(x=>x.includes('Guru Simulasi'))).toBe(true);expect(historyCalls).toBe(2);expect(errors).toEqual([]);await c.close();
});
