import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {database,root} from './helpers.mjs';
const schema=await fs.readFile(root+'sql/001-v4.sql','utf8');
const v3=await fs.readFile(root+'tests/fixtures/v3-schema.sql','utf8');
const upload=await fs.readFile(root+'tests/fixtures/v3-upload-schema.sql','utf8');
const seed=await fs.readFile(root+'tests/fixtures/v3-seed.sql','utf8');
test('upgrade dari GitHub v3 mempertahankan ID/data dan tidak menggandakan stok seed',async()=>{const db=await database({legacy:v3+seed,migrate:false});try{const before=(await db.query('select id from books order by id')).rows;await db.exec(schema);assert.deepEqual((await db.query('select id from books order by id')).rows,before);assert.equal((await db.query('select sum(tersedia)::int n from sinabos_stock')).rows[0].n,250);assert.equal((await db.query('select count(*)::int n from stock_movements')).rows[0].n,5);await assert.rejects(()=>db.query("insert into books(kode_buku,judul,kelas_target,total_buku) values('INVALID','X','VII',-1)"));}finally{await db.close();}});
test('upgrade lampiran menyimpan angka master lama sebagai review, bukan stok otomatis',async()=>{const db=await database({legacy:upload+seed,migrate:false});try{await db.exec("insert into books(kode_buku,judul,kelas_target,total_buku) values('MASTER-ONLY','Buku lama','VII',75)");await db.exec(schema);const b=(await db.query("select * from sinabos_stock where kode_buku='MASTER-ONLY'")).rows[0];assert.equal(b.legacy_total_buku,75);assert.equal(b.tersedia,0);assert.equal(b.needs_opening_review,true);}finally{await db.close();}});
test('migrasi rusak dari pengembalian memperbaiki 38 menjadi 40 tanpa menulis ulang ledger/history',async()=>{const db=await database({legacy:v3+seed,migrate:false});try{const id=(await db.query("select id from books where kode_buku='MTK-VII'")).rows[0].id;for(const [jenis,jumlah,kondisi] of [['pinjam',10,'baik'],['kembali',2,'rusak']])await db.query("select simpan_transaksi_scan('RBL-VII-A',$1,'Guru Lama',$2::jsonb)",[jenis,JSON.stringify([{buku_id:id,jumlah,kondisi}])]);assert.equal((await db.query('select tersedia from v_stok where id=$1',[id])).rows[0].tersedia,38);const before=(await db.query('select id,kode_transaksi,tanggal,nama_guru from circulation_transactions order by id')).rows;await db.exec(schema);assert.equal((await db.query('select tersedia from sinabos_stock where id=$1',[id])).rows[0].tersedia,40);assert.equal((await db.query('select tersedia from v_stok where id=$1',[id])).rows[0].tersedia,40);assert.deepEqual((await db.query('select id,kode_transaksi,tanggal,nama_guru from circulation_transactions order by id')).rows,before);await assert.rejects(()=>db.query("select simpan_transaksi_scan('RBL-VII-A','pinjam','Lama','[]'::jsonb)"),/API lama dinonaktifkan/);}finally{await db.close();}});
test('migrasi ambigu berhenti dan rollback seluruh DDL/data',async()=>{const db=await database({legacy:v3+seed,migrate:false});try{await db.exec("insert into stock_movements(buku_id,tipe,jumlah) select id,'hilang',1 from books limit 1");await assert.rejects(()=>db.exec(schema),/klasifikasikan/);await db.exec('rollback');assert.equal((await db.query("select to_regclass('public.sinabos_users') x")).rows[0].x,null);assert.equal((await db.query("select count(*)::int n from information_schema.columns where table_name='stock_movements' and column_name='available_delta'")).rows[0].n,0);}finally{await db.close();}});
test('saldo negatif lama tidak disembunyikan atau ditambal otomatis',async()=>{const db=await database({legacy:v3+seed,migrate:false});try{await db.exec("insert into stock_movements(buku_id,tipe,jumlah) select id,'pinjam',60 from books limit 1");await assert.rejects(()=>db.exec(schema),/saldo ledger negatif/);await db.exec('rollback');assert.equal((await db.query("select to_regclass('public.sinabos_users') x")).rows[0].x,null);}finally{await db.close();}});

test('preflight baca-saja valid pada kedua schema legacy tanpa menambah kolom',async()=>{
 for(const legacy of [v3,upload]){const db=await database({legacy:legacy+seed,migrate:false});try{await db.exec(await fs.readFile(root+'sql/000-preflight.sql','utf8'));assert.equal((await db.query("select count(*)::int n from information_schema.columns where table_name='stock_movements' and column_name='available_delta'")).rows[0].n,0);}finally{await db.close();}}
});
