import {csvCell} from './format.js';
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=v=>new Intl.NumberFormat('id-ID').format(Number(v)||0);
const paths={grid:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',scan:'M8 3H3v5 M16 3h5v5 M3 16v5h5 M21 16v5h-5 M7 7v10 M10 7v10 M14 7v10 M17 7v10',book:'M4 3h13a2 2 0 0 1 2 2v16H6a3 3 0 0 1-3-3V6a3 3 0 0 1 3-3 M3 18a3 3 0 0 1 3-3h13 M7 7h8 M7 10h6',history:'M3 12a9 9 0 1 0 3-7 M3 3v6h6 M12 7v5l3 2',clock:'M12 8v5l3 2 M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0',users:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2 M12 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0 M20 8v6 M17 11h6',school:'M3 21V9l9-6 9 6v12 M9 21v-6h6v6 M7 10h1 M16 10h1',report:'M6 3h9l4 4v14H6z M14 3v5h5 M9 12h7 M9 16h7',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M5 5l2 2 M17 17l2 2 M3 12h2 M19 12h2 M5 19l2-2 M17 7l2-2 M12 3v2 M12 19v2',arrow:'M5 12h14 M14 7l5 5-5 5',plus:'M12 5v14 M5 12h14',search:'M21 21l-6-6 M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0',refresh:'M3 10a9 9 0 0 1 16-5l2 2 M21 3v4h-4 M21 14a9 9 0 0 1-16 5l-2-2 M3 21v-4h4',camera:'M3 7h4l2-3h6l2 3h4v14H3z M16 14a4 4 0 1 1-8 0 4 4 0 0 1 8 0',check:'M5 12l4 4L19 6',download:'M12 3v12 M7 10l5 5 5-5 M4 17v4h16v-4',edit:'M14 5l5 5 M4 20l4-1L20 7a2 2 0 0 0-3-3L5 16z',shield:'M12 3l8 4v6c0 5-8 9-8 9s-8-4-8-9V7z M8 12l3 3 5-6',box:'M3 7l9-4 9 4v10l-9 4-9-4z M3 7l9 4 9-4 M12 11v10',close:'M6 6l12 12 M18 6L6 18',print:'M7 8V3h10v5 M7 17H3V8h18v9h-4 M7 13h10v8H7z',audit:'M7 3h10v18H5V3z M8 8h6 M8 12h6 M8 16h4'};
const icon=(name)=>`<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.book}"/></svg>`;
const navs=[['dashboard','Ringkasan','grid',true],['operasional','Transaksi Rombel','scan'],['books','Inventaris Buku','book',true],['history','Riwayat Transaksi','history'],['active','Peminjaman Aktif','clock',true],['rombel','Rombel & Barcode','school',true],['users','Akun Guru & Admin','users',true],['report','Laporan Bulanan','report',true],['audit','Log Aktivitas','audit',true],['settings','Pengaturan','settings']];
const S={authEpoch:0,user:null,view:'',date:'',cache:new Map(),flights:new Map(),rows:[],offset:0,limit:25,hasMore:false,cursors:[],cursor:null,query:'',klass:'',review:false,from:'',to:'',month:'',scan:null,items:[],receipt:null,pending:null,viewSeq:0,modalKind:'',lastLatency:0,cacheGeneration:0,qr:'',camera:null,reportRows:[]};
let debounceTimer, cameraGeneration=0, modalGeneration=0, scanGeneration=0;
const MUTATIONS=new Set(['circulate','saveBook','stockIn','stockLoss','saveRombel','saveUser','resetPassword','resetBooks']);
function setConnection(ok){const e=$('#connection');e.classList.toggle('offline',!ok);e.innerHTML=`<i class="status-dot"></i><span>${ok?'Terhubung':'Koneksi perlu diperiksa'}</span>`;}
function toast(message,type=''){const d=document.createElement('div');d.className='toast '+type;d.textContent=message;$('#toasts').append(d);setTimeout(()=>d.remove(),6000);}
function errorBox(form,error){const e=form?.querySelector('[data-error]');if(e){e.innerHTML=`<div class="error-box">${esc(error.message||error)}${error.requestId?`<br><small>ID bantuan: ${esc(error.requestId)}</small>`:''}</div>`;}else toast(error.message||error,'error');}
class APIError extends Error{constructor(message,code,status,id){super(message);this.code=code;this.status=status;this.requestId=id;}}
async function api(action,data={},options={}){
 const key=action+':'+JSON.stringify(data);const now=Date.now();const ttl=options.ttl||0;
 if(ttl && !options.fresh && S.cache.get(key)?.until>now)return S.cache.get(key).value;
 if(options.read && !options.fresh && S.flights.has(key))return S.flights.get(key);
 const generation=S.cacheGeneration,requestOwner=S.user?.id||null,authEpoch=S.authEpoch;
 const task=(async()=>{
  const ctrl=new AbortController();const timer=setTimeout(()=>ctrl.abort(),25000);const start=performance.now();
  try{
   const res=await fetch('/api',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-Sinabos-Request':'1'},body:JSON.stringify({action,data}),signal:ctrl.signal});
   let result;try{result=await res.json();}catch{throw new APIError('Respons layanan tidak dapat dibaca. Periksa status penyimpanan sebelum mengulang.','SERVICE_UNAVAILABLE',503);}
   if(requestOwner!==(S.user?.id||null)||authEpoch!==S.authEpoch)throw new APIError('Sesi akun telah berubah. Konfirmasi hasil melalui akun asal.', 'SESSION_CHANGED',401);
   S.lastLatency=Math.round(performance.now()-start);
   if(!res.ok || !result.ok){if(result.code==='UNAUTHENTICATED' && S.user && requestOwner===S.user.id)showLogin(true);throw new APIError(result.error||'Permintaan gagal',result.code||'SERVICE_UNAVAILABLE',res.status,result.request_id);}
   setConnection(true);if(result.server_date){S.date=result.server_date;$('#today-label').textContent=new Intl.DateTimeFormat('id-ID',{day:'numeric',month:'short',year:'numeric',timeZone:'Asia/Makassar'}).format(new Date(result.server_date+'T12:00:00+08:00'));}
   if(ttl && generation===S.cacheGeneration && requestOwner===(S.user?.id||null))S.cache.set(key,{value:result,until:Date.now()+ttl});return result;
  }catch(e){if(e instanceof APIError){if(e.status>=500)setConnection(false);throw e;}setConnection(false);throw new APIError('Koneksi terputus atau melewati batas waktu. Periksa status simpan sebelum mengirim ulang.','SERVICE_UNAVAILABLE',503);}
  finally{clearTimeout(timer);}
 })();
 if(options.read)S.flights.set(key,task);
 try{return await task;}finally{if(options.read && S.flights.get(key)===task)S.flights.delete(key);}
}
function invalidate(){S.cacheGeneration++;S.cache.clear();}
async function busy(button,label,fn){const original=button?.innerHTML;if(button){button.disabled=true;button.setAttribute('aria-busy','true');button.textContent=label;}
 try{return await fn();}finally{if(button){button.disabled=false;button.removeAttribute('aria-busy');button.innerHTML=original;}}
}
const pendingKey=()=>`sinabos.pending.${S.user?.id}`;
function storePending(){if(!S.pending)return;const p=structuredClone(S.pending);if(p.data.password!==undefined){p.needsPassword=true;delete p.data.password;}
 try{sessionStorage.setItem(pendingKey(),JSON.stringify(p));}catch{toast('Penyimpanan sementara browser tidak tersedia. Jangan tutup tab sampai status simpan pasti.','error');}}
function restorePending(){try{const p=JSON.parse(sessionStorage.getItem(pendingKey())||'null');if(p && MUTATIONS.has(p.action) && p.data?.request_id)S.pending=p;}catch{S.pending=null;}renderPending();}
function clearPending(){try{sessionStorage.removeItem(pendingKey());}catch{}S.pending=null;renderPending();}
function renderPending(){const e=$('#pending');e.hidden=!S.pending;if(!S.pending){e.innerHTML='';return;}e.innerHTML=`<section class="pending-card"><h3>Status penyimpanan perlu dipastikan</h3><p>Jangan membuat permintaan baru. Periksa hasil atau kirim ulang permintaan yang sama; sistem mencegah pencatatan ganda.</p><div class="actions"><button class="btn secondary small" data-action="pending-check">Periksa status</button><button class="btn soft small" data-action="pending-retry">Ulangi permintaan yang sama</button></div><code>ID: ${esc(S.pending.data.request_id)}</code></section>`;}
async function executePending(){const p=S.pending;if(!p)throw new Error('Tidak ada permintaan tertunda');
 try{const r=await api(p.action,p.data);clearPending();invalidate();return r;}
 catch(e){if(e.status<500 && e.status!==401 || e.code==='DATABASE_ERROR')clearPending();else renderPending();throw e;}}
async function mutate(action,data){if(S.pending)throw new Error('Pastikan hasil penyimpanan sebelumnya melalui panel di atas terlebih dahulu.');S.pending={action,data:{...data,request_id:crypto.randomUUID()}};storePending();return executePending();}
function recovered(r){if(r.receipt){S.receipt=r.receipt;S.scan=null;S.items=[];navigate('operasional',true);}else refreshCurrent();toast('Penyimpanan terkonfirmasi. Data tidak digandakan.','success');}
async function checkPending(button){await busy(button,'Memeriksa…',async()=>{const r=await api('requestStatus',{request_id:S.pending.data.request_id});if(r.found){clearPending();invalidate();recovered(r.result);}else toast('Belum ada hasil tersimpan. Gunakan ulangi permintaan yang sama; jangan buat transaksi baru.');});}
async function retryPending(button){if(S.pending.needsPassword && S.pending.data.password===undefined){showModal('Masukkan password sementara yang sama','Password tidak disimpan dalam browser.',`<form data-form="retry-secret"><label for="retry-password">Password pada permintaan sebelumnya</label><input id="retry-password" name="password" type="password" required autocomplete="new-password"><div data-error></div><div class="dialog-actions"><button class="btn primary">Ulangi permintaan</button></div></form>`);return;}
 await busy(button,'Mengonfirmasi…',async()=>{const r=await executePending();recovered(r);});}
function showLogin(expired=false){S.authEpoch++;stopCamera();modalGeneration++;S.modalForced=false;if($('#modal').open)$('#modal').close();$('#modal-content').replaceChildren();S.editing=null;S.qr='';S.qrName='';S.user=null;S.pending=null;invalidate();S.flights.clear();S.scan=null;S.items=[];S.receipt=null;S.rows=[];S.reportRows=[];S.view='';S.viewSeq++;$('#page').innerHTML='';$('#pending').innerHTML='';$('#pending').hidden=true;$('#app').hidden=true;$('#boot').hidden=true;$('#login').hidden=false;$('#login-form').reset();$('#password').type='password';const toggle=$('[data-action="toggle-password"]');toggle.textContent='Lihat';toggle.setAttribute('aria-label','Tampilkan password');closeMenu();$('#navigation').replaceChildren();for(const id of ['profile-name','profile-role','avatar'])$('#'+id).textContent='';$('#login-form [data-error]').innerHTML=expired?'<div class="notice warn">Sesi telah berakhir. Login kembali untuk melanjutkan.</div>':'';$('#username').focus();}
async function enter(user){S.authEpoch++;invalidate();S.flights.clear();S.user=user;$('#login').hidden=true;$('#boot').hidden=true;$('#app').hidden=false;$('#navigation').innerHTML=navs.filter(n=>!n[3]||user.role==='admin').map(n=>`<a class="nav-item" href="#${n[0]}" data-view="${n[0]}">${icon(n[2])}<span>${n[1]}</span></a>`).join('');$('#profile-name').textContent=user.full_name;$('#profile-role').textContent=user.role==='admin'?'ADMIN SEKOLAH':'AKUN GURU';$('#avatar').textContent=user.full_name.split(/\s+/).slice(0,2).map(n=>n[0]).join('').toUpperCase();restorePending();
 const selected=location.hash.slice(1);const view=navs.some(n=>n[0]===selected&&(!n[3]||user.role==='admin'))?selected:(user.role==='admin'?'dashboard':'operasional');
 if(user.must_change_password){S.view='settings';renderShell('settings');passwordModal(true);}else navigate(view,true);
}
function closeMenu(){$('#sidebar').classList.remove('open');$('.sidebar-scrim').hidden=true;}
function navigate(view,force=false){if(!S.user)return;const allowed=navs.find(n=>n[0]===view && (!n[3]||S.user.role==='admin'));if(!allowed)view=S.user.role==='admin'?'dashboard':'operasional';if(S.user.must_change_password){passwordModal(true);return;}if(location.hash!=='#'+view){location.hash=view;return;}if(S.view===view&&!force)return;stopCamera();closeMenu();S.view=view;S.viewSeq++;S.offset=0;S.cursors=[];S.cursor=null;S.query='';S.klass='';S.from='';S.to='';S.review=false;S.rows=[];$$('.nav-item').forEach(a=>a.classList.toggle('active',a.dataset.view===view));renderShell(view);awaitView();}
window.addEventListener('hashchange',()=>navigate(location.hash.slice(1)));
const header=(eyebrow,title,subtitle,buttons='')=>`<div class="page-header"><div><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${subtitle}</p></div>${buttons?`<div class="actions">${buttons}</div>`:''}</div>`;
const refreshButton=()=>`<button class="btn secondary" data-action="refresh" title="Muat data terbaru">${icon('refresh')}<span class="btn-label">Perbarui</span></button>`;
const addButton=(action,label)=>`<button class="btn primary" data-action="${action}">${icon('plus')}${label}</button>`;
const searchBar=placeholder=>`<div class="search">${icon('search')}<input id="search" type="search" maxlength="80" placeholder="${placeholder}" aria-label="${placeholder}"></div>`;
const loading=()=>`<div class="loading"><span class="spinner"></span>Memuat data yang Anda perlukan…</div>`;
const empty=(title='Belum ada data',subtitle='Data akan muncul setelah dicatat oleh sekolah.')=>`<div class="empty">${icon('book')}<strong>${esc(title)}</strong><p>${esc(subtitle)}</p></div>`;
function renderShell(view){const page=$('#page');
 if(view==='operasional'){page.innerHTML=header('LAYANAN HARI INI','Transaksi Rombel','Scan barcode, pilih buku, lalu simpan dengan akun Anda.')+`<div id="receipt-host"></div><div class="scan-layout"><div><section class="panel scan-panel"><div class="scan-title"><span class="icon-block">${icon('scan')}</span><div><h3>Mulai Dari Barcode Rombel</h3><p>Gunakan scanner USB, kamera, atau ketik kode.</p></div></div><form data-form="scan"><label for="barcode-input">Barcode Rombel</label><div class="input-group"><input id="barcode-input" name="barcode" placeholder="Contoh: RBL-VII-A" required maxlength="60" autocomplete="off" autocapitalize="characters"><button class="btn primary">Buka Form ${icon('arrow')}</button></div><div data-error></div></form><button class="btn secondary full camera-btn" data-action="camera-open">${icon('camera')}Pindai Dengan Kamera</button><div class="scan-help">${icon('shield')}<div><strong>Setiap transaksi tercatat atas nama Anda</strong><p>Periksa jumlah dan kondisi buku sebelum menyimpan.</p></div></div></section><div id="transaction-host"></div></div><aside class="flow-panel"><span class="eyebrow">ALUR LAYANAN</span><h3>Lebih Ringkas, Tetap Tertib</h3><div class="flow-step"><span>01</span><div><strong>KENALI ROMBEL</strong><p>Barcode menghubungkan transaksi ke kelas, bukan ke satu judul buku.</p></div></div><div class="flow-step"><span>02</span><div><strong>CATAT BUKU & KONDISI</strong><p>Beberapa mapel dapat dicatat sekaligus. Kondisi campuran dapat dipisahkan per baris.</p></div></div><div class="flow-step"><span>03</span><div><strong>SIMPAN BUKTI TRANSAKSI</strong><p>Tunggu konfirmasi dan kode transaksi. Jika koneksi putus, periksa status sebelum mengulang.</p></div></div><div class="identity-note">ANDA MENCATAT SEBAGAI<strong>${esc(S.user.full_name)}</strong>Identitas diambil dari akun, bukan isian bebas.</div></aside></div>`;renderReceipt();renderTransaction();return;}
 if(view==='dashboard'){page.innerHTML=header('DASHBOARD SEKOLAH','Ringkasan Buku','Gambaran persediaan dan layanan buku hari ini.',refreshButton())+'<div id="view-data">'+loading()+'</div>';return;}
 if(view==='settings'){page.innerHTML=header('AKUN & INFORMASI','Akun Dan Sistem','Kelola keamanan akun dan lihat status aplikasi.')+`<div class="account-grid"><section class="panel panel-pad"><h3>Identitas Akun</h3><dl class="info-list"><div><dt>Nama</dt><dd>${esc(S.user.full_name)}</dd></div><div><dt>Username</dt><dd>${esc(S.user.username)}</dd></div><div><dt>Peran</dt><dd>${S.user.role==='admin'?'Admin':'Guru'}</dd></div><div><dt>Sesi</dt><dd>Maksimum 8 jam</dd></div></dl><button class="btn soft" data-action="change-password">${icon('shield')}Ganti password</button><p class="footnote">Password baru menutup sesi perangkat lain. Jangan berbagi akun dengan pengguna lain.</p></section><section class="panel panel-pad"><h3>Informasi sistem</h3><dl class="info-list"><div><dt>Aplikasi</dt><dd>SINABOS 4.0.0</dd></div><div><dt>Tanggal sekolah</dt><dd>${esc(S.date)}</dd></div><div><dt>Zona waktu</dt><dd>Asia/Makassar · WITA</dd></div><div><dt>Respons terakhir di perangkat ini</dt><dd>${number(S.lastLatency)} ms</dd></div></dl><p class="footnote">Halaman memuat data sesuai kebutuhan. Saldo divalidasi kembali oleh database saat menyimpan. Angka respons dipengaruhi koneksi dan kondisi database, bukan jaminan kecepatan produksi.</p>${S.user.role==='admin'?'<button class="btn secondary" data-action="health">Periksa koneksi database</button>':''}<div id="health-result"></div></section></div>`;return;}
 const meta={books:['INVENTARIS SEKOLAH','Buku & Persediaan','Saldo bersumber dari mutasi; perubahan stok selalu memiliki catatan.',addButton('new-book','Tambah buku')+'<button class="btn danger small" data-action="reset-books">Reset data</button>'],history:['JEJAK LAYANAN','Riwayat Transaksi',S.user.role==='admin'?'Seluruh transaksi sekolah, dengan identitas pencatat terverifikasi.':'Transaksi yang dicatat menggunakan akun Anda.',''],active:['MONITORING ROMBEL','Peminjaman Aktif','Sisa buku dihitung per rombel, bukan utang pribadi guru.',''],rombel:['MASTER KELAS','Rombel & Barcode','Satu barcode membuka pilihan buku sesuai kelas.',addButton('new-rombel','Tambah rombel')],users:['PENGELOLAAN AKSES','Akun Guru / Admin','Akun pribadi untuk pencatatan yang dapat ditelusuri.',addButton('new-user','Tambah akun')],report:['ARSIP SEKOLAH','Laporan Bulanan','Rekap mutasi buku per bulan; unduh CSV untuk Excel atau Sheets.',''],audit:['JEJAK PERUBAHAN','Log Aktivitas','Aktivitas akun dan perubahan data, tanpa menyimpan password.','']}[view];
 let filters='';if(['books','active','users'].includes(view))filters=searchBar(view==='books'?'Cari kode, judul, atau mapel…':view==='active'?'Cari rombel atau judul buku…':'Cari nama atau username…');
 if(view==='books')filters+='<select id="filter-class" aria-label="Filter kelas"><option value="">Semua kelas</option><option>VII</option><option>VIII</option><option>IX</option></select>';
 if(view==='history')filters='<span class="muted">Rentang tanggal</span><input id="filter-from" type="date" aria-label="Dari tanggal"><span class="muted">—</span><input id="filter-to" type="date" aria-label="Sampai tanggal">';
 if(view==='report'){S.month=S.month||S.date.slice(0,7);filters=`<input id="filter-month" type="month" required value="${esc(S.month)}" aria-label="Bulan laporan"><button class="btn secondary small" data-action="download-report">${icon('download')}Unduh CSV</button>`;}
 page.innerHTML=header(meta[0],meta[1],meta[2],refreshButton()+meta[3])+`<section class="panel">${filters?`<div class="toolbar">${filters}</div>`:''}<div id="view-data">${loading()}</div><div id="pagination"></div></section>`;
}
function refreshCurrent(){if(!S.user)return;invalidate();if(S.view==='settings'){renderShell(S.view);return;}if(S.view==='operasional'){renderReceipt();return;}awaitView(true);}
async function awaitView(fresh=false){if(['operasional','settings'].includes(S.view))return;const seq=++S.viewSeq;const view=S.view;const data={limit:S.limit,offset:S.offset,q:S.query};if(view==='books'){data.kelas=S.klass;if(S.review)data.review=true;}if(view==='history'){if(S.cursor){data.cursor_time=S.cursor.created_at;data.cursor_id=S.cursor.id;}data.from=S.from;data.to=S.to;}if(view==='report')data.month=S.month;if(view==='audit'&&S.cursor)data.cursor=S.cursor.id;
 const el=$('#view-data');if(!el)return;el.setAttribute('aria-busy','true');
 try{const r=await api(view,data,{read:true,ttl:20000,fresh});if(seq!==S.viewSeq||view!==S.view)return;renderData(view,r);}
 catch(e){if(seq!==S.viewSeq||!S.user)return;el.innerHTML=`<div class="empty"><strong>Data belum berhasil dimuat</strong><p>${esc(e.message)}</p><button class="btn secondary small" data-action="refresh">Coba lagi</button></div>`;$('#pagination')?.replaceChildren();}
 finally{el.removeAttribute('aria-busy');}}
function table(headers,rows){return `<div class="table-scroll"><table><thead><tr>${headers.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div>`;}
function renderData(view,r){const el=$('#view-data');
 if(view==='dashboard'){el.innerHTML=`${r.review?`<div class="notice warn"><strong>${number(r.review)} buku lama perlu rekonsiliasi stok awal.</strong> Angka master tidak otomatis dijumlahkan agar stok tidak ganda. <button class="link-btn" data-action="review-books">Periksa buku →</button></div>`:''}<div class="stats">${[['Stok Tersedia',r.tersedia,'Eksemplar siap digunakan','box'],['Sedang Dipinjam',r.dipinjam,'Eksemplar di rombel','book'],['Transaksi Hari Ini',r.hari_ini,'Berdasarkan tanggal WITA','history'],['Jenis Buku Aktif',r.jenis,'Judul dalam inventaris','grid']].map(x=>`<div class="stat"><div class="stat-label">${x[0]}${icon(x[3])}</div><div class="stat-number">${number(x[1])}</div><span class="stat-note">${x[2]}</span></div>`).join('')}</div><section class="welcome-panel"><div><span class="eyebrow">LAYANAN YANG TERTATA</span><h2>Setiap buku, ada catatannya.</h2><p>Catat peminjaman dan pengembalian dalam satu alur. Identitas, kondisi, dan perubahan stok tersimpan bersama.</p><a class="btn primary" href="#operasional">Mulai Transaksi ${icon('arrow')}</a></div><div class="welcome-side"><div class="circle-book">${icon('book')}</div><p>Buku yang terkelola.<br>Kesempatan belajar<br>yang terjaga.</p></div></section><div class="section-label"><h2>Kelola Layanan Sekolah</h2><span>AKSES CEPAT</span></div><div class="quick-grid">${[['books','book','Inventaris Buku','Tambah master dan catat stok masuk.'],['active','clock','Pantau Peminjaman','Lihat sisa buku pada setiap rombel.'],['report','report','Rekap Bulanan','Unduh mutasi untuk arsip sekolah.']].map(x=>`<a class="quick-card" href="#${x[0]}"><span class="quick-icon">${icon(x[1])}</span><h3>${x[2]}</h3><p>${x[3]}</p></a>`).join('')}</div><div class="substats"><span>Akumulasi rusak: <b>${number(r.rusak)}</b></span><span>Akumulasi hilang: <b>${number(r.hilang)}</b></span><span>Saldo diperbarui atomik saat transaksi.</span></div>`;return;}
 S.hasMore=(r.rows?.length||0)>S.limit;S.rows=['rombel','report'].includes(view)?r.rows||[]:(r.rows||[]).slice(0,S.limit);const rows=S.rows;if(view==='report')S.reportRows=rows;
 if(!rows.length){el.innerHTML=empty(S.query||S.from||S.to?'Tidak ada hasil yang cocok':'Belum ada data',view==='history'?'Transaksi yang berhasil disimpan akan muncul di sini.':'Sesuaikan filter atau tambahkan data melalui tombol di atas.');renderPagination(view);return;}
 if(view==='books')el.innerHTML=table(['Buku / mapel','Kelas','Tersedia','Dipinjam','Perolehan','Tindakan'],rows.map((b,i)=>`<tr><td><div class="book-cell"><span class="book-cover">${esc(b.kelas_target)}</span><div><strong>${esc(b.judul)}</strong><small>${esc(b.kode_buku)} · ${esc(b.mata_pelajaran)}${b.isbn?` · ISBN ${esc(b.isbn)}`:''}${b.edisi?` · ${esc(b.edisi)}`:''}</small>${b.needs_opening_review?'<span class="badge orange">Periksa stok awal</span>':''}${!b.aktif?'<span class="badge gray">Nonaktif</span>':''}</div></div></td><td><span class="badge">${esc(b.kelas_target)}</span></td><td><span class="inventory-number amount">${number(b.tersedia)}</span><small>eksemplar</small></td><td class="amount">${number(b.dipinjam)}</td><td class="amount">${number(b.total_buku)}<small>Rusak ${number(b.total_rusak)} · Hilang ${number(b.total_hilang)}</small></td><td><div class="cell-actions"><button class="btn secondary small" data-action="edit-book" data-index="${i}">Edit</button><button class="btn soft small" data-action="stock-in" data-index="${i}">+ Stok</button><button class="icon-btn" data-action="stock-loss" data-index="${i}" title="Catat rusak/hilang dari rak" aria-label="Catat rusak atau hilang dari rak">−</button></div></td></tr>`).join(''));
 if(view==='history')el.innerHTML=table(['Transaksi','Tanggal WITA','Rombel / pencatat','Rincian buku'],rows.map((t,i)=>`<tr><td><span class="badge ${t.jenis_transaksi==='pinjam'?'':'green'}">${t.jenis_transaksi==='pinjam'?'Peminjaman':'Pengembalian'}</span><small title="${esc(t.kode_transaksi)}">${esc(t.kode_transaksi.slice(0,21))}…</small><button class="link-btn" data-action="history-receipt" data-index="${i}">Lihat bukti</button></td><td class="date-cell">${esc(t.tanggal)}<small>${formatTime(t.created_at)}</small></td><td><strong>${esc(t.rombel)}</strong><small>${esc(t.nama_guru)}</small></td><td class="loan-detail">${(t.items||[]).map(x=>`${esc(x.judul)} ×<b>${number(x.jumlah)}</b> <span class="badge ${x.kondisi==='baik'?'gray':'orange'}">${esc(x.kondisi)}</span>`).join('<br>')}</td></tr>`).join(''));
 if(view==='active')el.innerHTML=table(['Rombel','Buku','Dipinjam','Diselesaikan','Sisa','Pelaku terakhir'],rows.map(a=>`<tr><td><strong>${esc(a.rombel)}</strong><small>${esc(a.barcode)}</small></td><td>${esc(a.judul)}</td><td>${number(a.total_pinjam)}</td><td>${number(a.total_kembali)}</td><td><span class="inventory-number">${number(a.sisa)}</span></td><td>${esc(a.pelaku_terakhir)}<small>${formatDateTime(a.updated_at)}</small></td></tr>`).join(''));
 if(view==='rombel')el.innerHTML=table(['Rombel','Barcode','Kelas','Status','Tindakan'],rows.map((a,i)=>`<tr><td><strong>${esc(a.rombel)}</strong><small>${esc(a.keterangan)}</small></td><td><code>${esc(a.barcode)}</code></td><td><span class="badge">${esc(a.kelas_target)}</span></td><td><span class="badge ${a.aktif?'green':'gray'}">${a.aktif?'Aktif':'Nonaktif'}</span></td><td class="cell-actions"><button class="btn secondary small" data-action="edit-rombel" data-index="${i}">Edit</button><button class="btn soft small" data-action="label" data-index="${i}">${icon('scan')}Label QR</button></td></tr>`).join(''));
 if(view==='users')el.innerHTML=table(['Nama pengguna','Peran','Status','Keamanan','Tindakan'],rows.map((a,i)=>`<tr><td><strong>${esc(a.full_name)}</strong><small>@${esc(a.username)}</small></td><td><span class="badge ${a.role==='admin'?'':'gray'}">${esc(a.role)}</span></td><td><span class="badge ${a.active?'green':'red'}">${a.active?'Aktif':'Nonaktif'}</span></td><td><small>${a.must_change_password?'Wajib ganti password':'Password pribadi'}</small></td><td class="cell-actions"><button class="btn secondary small" data-action="edit-user" data-index="${i}">Edit</button>${a.id!==S.user.id?`<button class="btn soft small" data-action="reset-user" data-index="${i}">Reset sandi</button>`:''}</td></tr>`).join(''));
 if(view==='report'){S.reportRows=rows;el.innerHTML=table(['Kode / judul','Masuk','Pinjam','Kembali baik','Rusak','Hilang','Δ tersedia'],rows.map(a=>`<tr><td><strong>${esc(a.kode_buku)}</strong><small>${esc(a.judul)}</small></td><td>${number(a.masuk)}</td><td>${number(a.pinjam)}</td><td>${number(a.kembali_baik)}</td><td>${number(a.rusak)}</td><td>${number(a.hilang)}</td><td>${number(a.perubahan_tersedia)}</td></tr>`).join(''))+'<div class="table-meta">Rusak/hilang dapat berasal dari penyelesaian pinjaman atau kejadian di rak. Kolom Δ tersedia memakai dampak ledger sebenarnya, bukan mengurangkan kerusakan dua kali.</div>';}
 if(view==='audit')el.innerHTML=table(['Waktu WITA','Pelaku','Aktivitas','Catatan'],rows.map(a=>`<tr><td class="date-cell">${formatDateTime(a.created_at)}</td><td>${esc(a.full_name||'Sistem')}</td><td><span class="badge gray">${esc(a.action)}</span></td><td>${esc(a.detail?.catatan||'—')}<small>${a.detail?.jumlah?number(a.detail.jumlah)+' buku':''}</small></td></tr>`).join(''));
 renderPagination(view);
}
function formatTime(v){try{return new Intl.DateTimeFormat('id-ID',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Makassar'}).format(new Date(v));}catch{return '—';}}
function formatDateTime(v){try{return new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Makassar'}).format(new Date(v));}catch{return '—';}}
function renderPagination(view){const el=$('#pagination');if(!el)return;if(['rombel','report'].includes(view)){el.innerHTML=`<div class="table-meta">${number(S.rows.length)} ${view==='rombel'?'rombel':'jenis buku'} ditampilkan.</div>`;return;}const prev=['history','audit'].includes(view)?S.cursors.length>0:S.offset>0;el.innerHTML=`<div class="pagination"><span>${number(S.rows.length)} baris · dimuat sesuai kebutuhan</span><div class="actions"><button class="btn secondary small" data-action="prev-page" ${prev?'':'disabled'}>← Sebelumnya</button><button class="btn secondary small" data-action="next-page" ${S.hasMore?'':'disabled'}>Berikutnya →</button></div></div>`;}
function renderTransaction(){const host=$('#transaction-host');if(!host)return;if(!S.scan){host.innerHTML='';return;}const r=S.scan.rombel;const kind=S.scan.kind||'pinjam';host.innerHTML=`<section class="panel tx-form"><div class="rombel-banner"><div><span class="eyebrow">FORM TRANSAKSI</span><strong>Rombel ${esc(r.rombel)}</strong><small>${esc(r.barcode)} · Kelas ${esc(r.kelas_target)}</small></div><div>Tanggal sekolah<br><b>${esc(S.date)}</b></div></div><form data-form="circulate"><div class="form-grid"><div><label for="tx-kind">Jenis transaksi</label><select id="tx-kind" name="jenis_transaksi"><option value="pinjam" ${kind==='pinjam'?'selected':''} ${r.aktif?'':'disabled'}>Peminjaman</option><option value="kembali" ${kind==='kembali'?'selected':''}>Pengembalian</option></select></div><div><label for="tx-name">Nama pencatat</label><input id="tx-name" value="${esc(S.user.full_name)}" readonly></div></div><div class="items-head"><h3>Buku / mapel</h3><button class="btn soft small" type="button" data-action="add-item">${icon('plus')}Tambah baris</button></div><div id="items"></div><div class="field-help">${kind==='kembali'?'Kondisi berbeda untuk buku yang sama boleh dicatat dalam baris terpisah. Sisa adalah saldo seluruh rombel.':'Hanya buku aktif dengan kondisi baik yang dapat dipinjam.'}</div><div data-error></div><div class="form-bottom"><span class="left">Saldo diperiksa kembali saat menyimpan.</span><button class="btn secondary" type="button" data-action="cancel-tx">Batal</button><button class="btn primary" type="submit">Simpan transaksi ${icon('check')}</button></div></form></section>`;renderItems();}
function optionsBooks(){return (S.scan?.books||[]).filter(b=>S.scan.kind==='kembali'?Number(b.sisa)>0:b.can_borrow);}
function renderItems(){const el=$('#items');if(!el)return;const kind=S.scan.kind||'pinjam';const books=optionsBooks();el.innerHTML=!books.length?empty('Tidak ada buku untuk transaksi ini',kind==='kembali'?'Rombel ini tidak memiliki sisa pinjaman.':'Hubungi admin untuk menambahkan buku sesuai kelas.'):S.items.map((item,i)=>`<div class="item-row"><div class="book-field"><label for="item-book-${i}">Buku / mapel ${i+1}</label><select id="item-book-${i}" data-item="${i}" data-field="buku_id" required><option value="">Pilih buku…</option>${books.map(b=>`<option value="${esc(b.id)}" ${item.buku_id===b.id?'selected':''}>${esc(b.judul)} · ${kind==='kembali'?'sisa '+number(b.sisa):'tersedia '+number(b.tersedia)}</option>`).join('')}</select></div><div><label for="item-qty-${i}">Jumlah</label><input id="item-qty-${i}" data-item="${i}" data-field="jumlah" type="number" min="1" max="100000" step="1" required value="${esc(item.jumlah)}"></div><div><label for="item-condition-${i}">Kondisi</label><select id="item-condition-${i}" data-item="${i}" data-field="kondisi" ${kind==='pinjam'?'disabled':''}>${['baik','rusak','hilang'].map(c=>`<option value="${c}" ${item.kondisi===c?'selected':''}>${c[0].toUpperCase()+c.slice(1)}</option>`).join('')}</select></div><button class="icon-btn" type="button" data-action="remove-item" data-index="${i}" aria-label="Hapus baris ${i+1}">${icon('close')}</button></div>`).join('');}
function receiptHTML(t,modal=false){return `<div class="receipt"><div class="receipt-title"><span>${icon('check')}</span><div><h3>Transaksi tersimpan</h3><p>${t.jenis_transaksi==='pinjam'?'Peminjaman':'Pengembalian'} · Rombel ${esc(t.rombel)}</p></div></div><code class="receipt-code">${esc(t.kode_transaksi)}</code><div class="receipt-meta"><span>${esc(t.nama_guru)}</span><span>${esc(t.tanggal)} · ${formatTime(t.created_at)} WITA</span></div><ul class="receipt-items">${(t.items||[]).map(x=>`<li>${esc(x.judul)} · <b>${number(x.jumlah)} buku</b> · ${esc(x.kondisi)}</li>`).join('')}</ul><div class="form-bottom"><button class="btn secondary small" data-action="${modal?'print-modal':'print-receipt'}">${icon('print')}Cetak bukti</button>${modal?'':'<button class="btn soft small" data-action="new-tx">Transaksi baru →</button>'}</div></div>`;}
function renderReceipt(){const el=$('#receipt-host');if(el)el.innerHTML=S.receipt?receiptHTML(S.receipt):'';}
const input=(name,label,value='',extra='')=>`<div><label for="f-${name}">${label}</label><input id="f-${name}" name="${name}" value="${esc(value)}" ${extra}></div>`;
const classSelect=value=>`<div><label for="f-kelas_target">Kelas</label><select id="f-kelas_target" name="kelas_target">${['VII','VIII','IX'].map(c=>`<option ${c===value?'selected':''}>${c}</option>`).join('')}</select></div>`;
const dialogActions=(label='Simpan')=>`<div data-error role="alert"></div><div class="dialog-actions"><button class="btn secondary" type="button" data-action="close-modal">Batal</button><button class="btn primary" type="submit">${label}</button></div>`;
function showModal(title,subtitle,body,forced=false){const generation=++modalGeneration;S.modalForced=forced;const d=$('#modal');$('#modal-content').innerHTML=`<div class="dialog-head"><div><span class="eyebrow">SINABOS · LAYANAN SEKOLAH</span><h2 id="modal-title">${esc(title)}</h2>${subtitle?`<p>${esc(subtitle)}</p>`:''}</div>${forced?'':`<button class="icon-btn" data-action="close-modal" aria-label="Tutup">${icon('close')}</button>`}</div>${body}`;if(!d.open)d.showModal();setTimeout(()=>{if(generation===modalGeneration)d.querySelector('input:not([type=hidden]),select,button[type=submit]')?.focus();},20);}
function closeModal(){if(S.modalForced)return;modalGeneration++;$('#modal').close();$('#modal-content').replaceChildren();S.editing=null;}
$('#modal').addEventListener('cancel',e=>{if(S.modalForced)e.preventDefault();});
function bookModal(book=null){S.editing=book;showModal(book?'Edit data buku':'Tambah buku baru',book?'Perubahan master tidak mengubah saldo. Gunakan + Stok untuk penambahan.':'Master dan stok awal disimpan sekaligus dalam satu transaksi.',`<form data-form="book"><div class="form-grid">${input('kode_buku','Kode buku',book?.kode_buku,'required maxlength="60"')}${input('judul','Judul buku',book?.judul,'required maxlength="200"')}${classSelect(book?.kelas_target)}${input('mata_pelajaran','Mata pelajaran',book?.mata_pelajaran,'required maxlength="100"')}${input('tahun_terbit','Tahun terbit',book?.tahun_terbit||S.date.slice(0,4)||String(new Date().getFullYear()),'type="number" min="1900" max="2099" step="1" required')}${input('kurikulum','Kurikulum',book?.kurikulum||'Merdeka','required maxlength="100"')}${input('penulis','Penulis',book?.penulis,'required maxlength="150"')}${input('penerbit','Penerbit',book?.penerbit,'required maxlength="150"')}${input('isbn','ISBN (opsional)',book?.isbn,'maxlength="32" inputmode="numeric" placeholder="978-602-…"')}${input('edisi','Edisi (opsional)',book?.edisi,'maxlength="40" placeholder="Edisi ke-3, cetakan revisi, …"')}${input('sumber_buku','Sumber buku',book?.sumber_buku||book?.sumber_dana||'BOS','required maxlength="150"')}${book?`<div><label>Status buku</label><label class="check-label"><input name="aktif" type="checkbox" ${book.aktif?'checked':''}>Aktif untuk peminjaman baru</label></div>`:input('total_awal','Stok awal (eksemplar)',0,'type="number" min="0" max="100000" step="1" required')}</div>${book?.needs_opening_review?'<div class="notice warn">Buku ini memerlukan rekonsiliasi stok awal. Periksa fisik buku, lalu gunakan tombol + Stok.</div>':''}${dialogActions(book?'Simpan perubahan':'Simpan buku & stok awal')}</form>`);}
function stockModal(book,loss=false){S.editing=book;showModal(loss?'Rusak / hilang dari rak':'Catat stok masuk',book.judul,`<form data-form="${loss?'stock-loss':'stock-in'}"><div class="notice">Tersedia di rak: <b>${number(book.tersedia)} eksemplar</b>. ${loss?'Untuk buku yang sedang dipinjam, gunakan Pengembalian agar saldo rombel ikut diselesaikan.':'Penambahan dicatat sebagai mutasi, bukan menimpa total sebelumnya.'}</div><div class="form-grid">${input('jumlah','Jumlah buku',1,'type="number" min="1" max="100000" step="1" required')}${loss?'<div><label>Kondisi</label><select name="kondisi"><option value="rusak">Rusak</option><option value="hilang">Hilang</option></select></div>':input('sumber_perolehan','Sumber perolehan',book.sumber_buku||'BOS','required maxlength="150"')}</div><label for="stock-note">Alasan / catatan</label><textarea id="stock-note" name="keterangan" required maxlength="300" placeholder="Sumber, tanggal pemeriksaan fisik, atau alasan perubahan"></textarea>${!loss&&book.needs_opening_review?`<div class="notice warn">Master lama mencatat ${number(book.legacy_total_buku)} buku, tetapi belum memiliki mutasi masuk. Angka tersebut tidak otomatis dijumlahkan.</div><label class="check-label"><input name="acknowledge_legacy" type="checkbox" required>Saya telah memeriksa stok fisik. Jumlah di atas adalah stok awal yang benar, bukan penambahan ganda.</label>`:''}${dialogActions(loss?'Catat kejadian':'Simpan stok masuk')}</form>`);}
function rombelModal(row=null){S.editing=row;showModal(row?'Edit rombel':'Tambah rombel','Gunakan kode singkat yang dapat dicetak pada label.',`<form data-form="rombel"><div class="form-grid">${input('barcode','Barcode',row?.barcode,'required maxlength="60" pattern="[A-Za-z0-9_-]{3,60}" placeholder="RBL-VII-A"')}${input('rombel','Nama rombel',row?.rombel,'required maxlength="40" placeholder="VII-A"')}${classSelect(row?.kelas_target)}${input('keterangan','Keterangan',row?.keterangan,'maxlength="200"')}</div>${row?`<label class="check-label"><input name="aktif" type="checkbox" ${row.aktif?'checked':''}>Aktif</label>`:''}${dialogActions()}</form>`);}
function randomPassword(){return 'Buku-'+crypto.randomUUID().replace(/-/g,'').slice(0,14)+'!';}
function userModal(row=null,reset=false){S.editing=row;const temp=randomPassword();showModal(reset?'Reset password akun':row?'Edit akun':'Tambah akun pribadi',reset?row.full_name:'Akun guru tidak dapat mengelola master atau melihat seluruh riwayat sekolah.',`<form data-form="${reset?'reset-user':'user'}">${reset?'':`<div class="form-grid">${input('username','Username',row?.username,'required pattern="[a-z0-9][a-z0-9._-]{2,39}" maxlength="40" autocomplete="off"')}${input('full_name','Nama lengkap',row?.full_name,'required minlength="2" maxlength="100"')}<div><label>Peran</label><select name="role"><option value="guru" ${row?.role==='guru'?'selected':''}>Guru</option><option value="admin" ${row?.role==='admin'?'selected':''}>Admin</option></select></div>${row?`<div><label>Status</label><label class="check-label"><input name="active" type="checkbox" ${row.active?'checked':''}>Akun aktif</label></div>`:''}</div>`}${!row||reset?`${input('password','Password sementara',temp,'required minlength="12" autocomplete="new-password"')}<p class="field-help">Catat dan bagikan secara pribadi. Pengguna wajib mengganti password saat pertama masuk. Maksimum 72 byte UTF-8.</p>`:''}${dialogActions(reset?'Reset & tutup sesi lama':row?'Simpan perubahan':'Buat akun')}</form>`);}
function passwordModal(forced=false){showModal(forced?'Buat password pribadi Anda':'Ganti password',forced?'Password sementara hanya untuk masuk pertama kali.':'Sesi pada perangkat lain akan ditutup.',`<form data-form="password">${input('old_password','Password saat ini','','type="password" required autocomplete="current-password"')}${input('new_password','Password baru','','type="password" required minlength="12" autocomplete="new-password"')}${input('confirm_password','Ulangi password baru','','type="password" required minlength="12" autocomplete="new-password"')}<div class="field-help">Gunakan minimal 12 karakter, maksimal 72 byte UTF-8. Pilih frasa sandi yang panjang dan unik.</div><div data-error></div><div class="dialog-actions">${forced?'':'<button class="btn secondary" type="button" data-action="close-modal">Batal</button>'}<button class="btn primary">Simpan password</button></div></form>`,forced);}
async function labelModal(row){showModal('Label rombel',row.rombel,loading());const generation=modalGeneration;try{const qrModule=await import('qrcode');const qr=qrModule.default||qrModule;const svg=await qr.toString(row.barcode,{type:'svg',width:256,margin:2,errorCorrectionLevel:'M'});if(generation!==modalGeneration||!$('#modal').open)return;S.qr=svg;S.qrName=row.barcode;$('#modal-content').innerHTML=`<div class="dialog-head"><h2 id="modal-title">Label rombel</h2><button class="icon-btn" data-action="close-modal" aria-label="Tutup">×</button></div><div class="qr-label print-area"><span class="eyebrow">SMP LABSCHOOL UNTAD PALU</span>${S.qr}<h3>${esc(row.rombel)}</h3><p>${esc(row.barcode)}</p><p>Scan untuk mencatat peminjaman / pengembalian buku.</p></div><div class="dialog-actions"><button class="btn secondary" data-action="download-qr">${icon('download')}SVG</button><button class="btn primary" data-action="print-modal">${icon('print')}Cetak label</button></div>`;}catch{if(generation===modalGeneration&&$('#modal').open)showModal('Label belum dapat dibuat','Muat ulang halaman lalu coba lagi.', '<div class="error-box">Komponen QR belum berhasil dimuat. Data rombel tidak berubah.</div><div class="dialog-actions"><button class="btn secondary" data-action="close-modal">Tutup</button></div>');}}
function downloadFile(content,filename,type){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportReport(){if(!S.reportRows.length){toast('Tidak ada data untuk diekspor.');return;}const keys=['kode_buku','judul','kelas_target','masuk','pinjam','kembali_baik','rusak','hilang','perubahan_tersedia','sumber'];const lines=[['Kode','Judul','Kelas','Masuk','Pinjam','Kembali baik','Rusak','Hilang','Perubahan tersedia','Sumber'],...S.reportRows.map(r=>keys.map(k=>r[k]))];downloadFile('\uFEFF'+lines.map(r=>r.map(csvCell).join(';')).join('\r\n'),'SINABOS-mutasi-'+S.month+'.csv','text/csv;charset=utf-8');}
async function startCamera(){const generation=++cameraGeneration;const dialog=$('#camera-dialog');if(!dialog.open)dialog.showModal();$('#camera-message').textContent='Meminta izin kamera…';const video=$('#camera-video');
 try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Kamera memerlukan HTTPS dan browser yang mendukung. Gunakan input manual atau scanner USB.');
  let formats=[];if('BarcodeDetector'in window)formats=await BarcodeDetector.getSupportedFormats();
  if(generation!==cameraGeneration)return;
  const supported=['qr_code','code_128','ean_13','ean_8'].filter(f=>formats.includes(f));
  if(supported.length){const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});if(generation!==cameraGeneration){stream.getTracks().forEach(t=>t.stop());return;}S.camera={stop:()=>stream.getTracks().forEach(t=>t.stop())};video.srcObject=stream;await video.play();const detector=new BarcodeDetector({formats:supported});$('#camera-message').textContent='Kamera aktif. Posisikan barcode di dalam bingkai.';
   const loop=async()=>{if(generation!==cameraGeneration)return;try{const found=await detector.detect(video);if(generation!==cameraGeneration)return;if(found.length){cameraDetected(found[0].rawValue);return;}}catch{}setTimeout(loop,140);};loop();
  }else{const {BrowserMultiFormatReader}=await import('@zxing/browser');if(generation!==cameraGeneration)return;const reader=new BrowserMultiFormatReader();const controls=await reader.decodeFromConstraints({video:{facingMode:{ideal:'environment'}}},video,(result)=>{if(result&&generation===cameraGeneration)cameraDetected(result.getText());});if(generation!==cameraGeneration){controls.stop();return;}S.camera=controls;$('#camera-message').textContent='Kamera aktif dengan pemindai kompatibilitas.';}
 }catch(e){if(generation===cameraGeneration){S.camera?.stop?.();S.camera=null;if(video.srcObject){video.srcObject.getTracks().forEach(t=>t.stop());video.srcObject=null;}$('#camera-message').textContent=e.name==='NotAllowedError'?'Izin kamera ditolak. Izinkan kamera pada pengaturan browser, atau gunakan input manual.':e.message;}}}
function stopCamera(){cameraGeneration++;S.camera?.stop?.();S.camera=null;const v=$('#camera-video');if(v?.srcObject){v.srcObject.getTracks().forEach(t=>t.stop());v.srcObject=null;}if($('#camera-dialog').open)$('#camera-dialog').close();}
async function cameraDetected(value){stopCamera();const input=$('#barcode-input');if(!S.user||S.view!=='operasional'||!input)return;input.value=value;try{await lookup(value);}catch(e){errorBox($('[data-form="scan"]'),e);}}
$('#camera-dialog').addEventListener('cancel',stopCamera);window.addEventListener('pagehide',stopCamera);
async function lookup(barcode){const seq=++scanGeneration,viewSeq=S.viewSeq,owner=S.user?.id;const r=await api('scan',{barcode:barcode.trim()});if(seq!==scanGeneration||viewSeq!==S.viewSeq||owner!==S.user?.id)return;S.scan={...r,kind:r.rombel.aktif?'pinjam':'kembali'};S.items=[{buku_id:'',jumlah:1,kondisi:'baik'}];S.receipt=null;renderReceipt();renderTransaction();$('#transaction-host')?.scrollIntoView({behavior:'smooth',block:'nearest'});}
function validateItems(){if(!S.items.length)throw new Error('Tambahkan minimal satu baris buku.');if(S.items.length>30)throw new Error('Maksimum 30 baris per transaksi.');const seen=new Set(),total=new Map();for(const [i,x] of S.items.entries()){if(!x.buku_id||!Number.isSafeInteger(Number(x.jumlah))||Number(x.jumlah)<1||Number(x.jumlah)>100000)throw new Error(`Periksa buku dan jumlah bilangan bulat pada baris ${i+1}. Tidak ada baris yang dibuang otomatis.`);const k=x.buku_id+':'+x.kondisi;if(seen.has(k))throw new Error('Gabungkan baris buku dengan kondisi yang sama.');seen.add(k);total.set(x.buku_id,(total.get(x.buku_id)||0)+Number(x.jumlah));}
 for(const [id,n] of total){const b=S.scan.books.find(x=>x.id===id);if(!b)throw new Error('Pilihan buku tidak tersedia. Pindai ulang barcode.');const max=Number(S.scan.kind==='kembali'?b.sisa:b.tersedia);if(n>max)throw new Error(`${b.judul}: jumlah ${n} melebihi ${S.scan.kind==='kembali'?'sisa':'tersedia'} ${max}. Pindai ulang bila saldo baru berubah.`);}
 return S.items.map(x=>({buku_id:x.buku_id,jumlah:Number(x.jumlah),kondisi:x.kondisi}));}
document.addEventListener('submit',async event=>{const form=event.target.closest('form[data-form]');if(!form)return;event.preventDefault();if(!form.reportValidity())return;form.querySelector('[data-error]')?.replaceChildren();const data=Object.fromEntries(new FormData(form));const type=form.dataset.form;const button=event.submitter||form.querySelector('button[type=submit],button:not([type])');
 try{await busy(button,type==='login'?'Memverifikasi…':'Memproses…',async()=>{
  if(type==='login'){const r=await api('login',{username:data.username.trim(),password:data.password});form.reset();await enter(r.user);return;}
  if(type==='scan'){await lookup(data.barcode);return;}
  if(type==='circulate'){if(!S.scan)throw new Error('Pindai barcode terlebih dahulu.');const items=validateItems();const r=await mutate('circulate',{barcode:S.scan.rombel.barcode,jenis_transaksi:S.scan.kind,items});S.receipt=r.receipt;S.scan=null;S.items=[];renderReceipt();renderTransaction();$('#receipt-host').scrollIntoView({behavior:'smooth'});toast('Transaksi tersimpan. Bukti tersedia di halaman ini.','success');return;}
  if(type==='password'){if(data.new_password!==data.confirm_password)throw new Error('Konfirmasi password baru belum sama.');await api('changePassword',{old_password:data.old_password,new_password:data.new_password});S.authEpoch++;S.flights.clear();S.user.must_change_password=false;S.modalForced=false;closeModal();invalidate();toast('Password diganti. Sesi perangkat lain ditutup.','success');navigate(S.user.role==='admin'?'dashboard':'operasional',true);return;}
  if(type==='retry-secret'){S.pending.data.password=data.password;const r=await executePending();closeModal();recovered(r);return;}
  let result;
  if(type==='book'){const payload={...data};if(S.editing){payload.id=S.editing.id;payload.revision=S.editing.revision;payload.aktif=form.elements.aktif.checked;}else payload.total_awal=Number(data.total_awal);result=await mutate('saveBook',payload);}
  if(type==='stock-in'||type==='stock-loss'){result=await mutate(type==='stock-in'?'stockIn':'stockLoss',{...data,buku_id:S.editing.id,jumlah:Number(data.jumlah),acknowledge_legacy:form.elements.acknowledge_legacy?.checked||false});}
  if(type==='rombel'){const payload={...data};if(S.editing){payload.id=S.editing.id;payload.revision=S.editing.revision;payload.aktif=form.elements.aktif.checked;}result=await mutate('saveRombel',payload);}
  if(type==='user'){const payload={...data};if(S.editing){payload.id=S.editing.id;payload.revision=S.editing.revision;payload.active=form.elements.active.checked;}result=await mutate('saveUser',payload);}
  if(type==='reset-user')result=await mutate('resetPassword',{id:S.editing.id,password:data.password});
  if(type==='reset-books'){if(!form.elements.confirm.checked)throw new Error('Centang konfirmasi terlebih dahulu.');const r=await mutate('resetBooks',{});closeModal();toast(`Data buku direset: ${r.reset.buku} buku dan ${r.reset.mutasi} mutasi dihapus. Silakan input master baru.`,'success');refreshCurrent();return;}
  if(result){const secret=data.password;const username=data.username||S.editing?.username;const ownEdit=type==='user'&&S.editing?.id===S.user.id;if(ownEdit){S.user.full_name=data.full_name;S.user.username=data.username;$('#profile-name').textContent=data.full_name;}
   closeModal();toast('Data berhasil disimpan.','success');refreshCurrent();
   if(secret)showModal('Akun berhasil diperbarui','Bagikan password sementara secara pribadi, bukan di grup umum.',`<div class="notice">Username: <b>${esc(username)}</b></div><p class="field-help">Password sementara</p><div class="sensitive-password">${esc(secret)}</div><p class="dialog-body-note">Pengguna wajib mengganti password setelah login. Password ini tidak ditampilkan kembali setelah jendela ditutup.</p><div class="dialog-actions"><button class="btn primary" data-action="close-modal">Sudah dicatat</button></div>`);
  }
 });}catch(e){errorBox(form,e);}
});
document.addEventListener('input',event=>{const el=event.target;if(el.dataset.item!==undefined && el.dataset.field){const item=S.items[Number(el.dataset.item)];if(item)item[el.dataset.field]=el.value;}
 if(el.id==='search'){S.query=el.value;S.offset=0;clearTimeout(debounceTimer);debounceTimer=setTimeout(()=>awaitView(),280);}});
document.addEventListener('change',event=>{const el=event.target;if(el.dataset.item!==undefined && el.dataset.field){const item=S.items[Number(el.dataset.item)];if(item)item[el.dataset.field]=el.value;}
 if(el.id==='tx-kind'){S.scan.kind=el.value;S.items=[{buku_id:'',jumlah:1,kondisi:'baik'}];renderTransaction();}
 if(el.id==='filter-class'){S.klass=el.value;S.offset=0;awaitView();}
 if(el.id==='filter-from'||el.id==='filter-to'){S.from=$('#filter-from').value;S.to=$('#filter-to').value;S.cursors=[];S.cursor=null;if(S.from&&S.to&&S.from>S.to){toast('Tanggal awal harus sebelum tanggal akhir.','error');return;}awaitView();}
 if(el.id==='filter-month'){if(!el.value)return;S.month=el.value;S.reportRows=[];awaitView();}});
document.addEventListener('click',async event=>{const b=event.target.closest('[data-action]');if(!b||b.disabled)return;const action=b.dataset.action;const row=S.rows[Number(b.dataset.index)];
 try{
  if(action==='toggle-password'){const input=document.getElementById(b.dataset.target);input.type=input.type==='password'?'text':'password';b.textContent=input.type==='password'?'Lihat':'Sembunyikan';b.setAttribute('aria-label',input.type==='password'?'Tampilkan password':'Sembunyikan password');}
  if(action==='menu'){$('#sidebar').classList.toggle('open');$('.sidebar-scrim').hidden=!$('#sidebar').classList.contains('open');}
  if(action==='close-menu')closeMenu();
  if(action==='logout'){if(S.pending)throw new Error('Konfirmasi penyimpanan tertunda sebelum keluar agar bukti transaksi tidak hilang.');await busy(b,'Menutup sesi…',()=>api('logout'));try{for(const k of Object.keys(sessionStorage))if(k.startsWith('sinabos.'))sessionStorage.removeItem(k);}catch{}showLogin();}
  if(action==='refresh')refreshCurrent();
  if(action==='new-book')bookModal();if(action==='reset-books')showModal('Reset data buku?','Semua buku, stok, dan mutasi masuk dihapus; input dimulai dari nol.',`<form data-form="reset-books"><div class="notice warn">Hanya dapat dilakukan <b>sebelum ada transaksi tersimpan</b>. Rombel, barcode, dan akun tidak ikut dihapus.</div><label class="check-label"><input name="confirm" type="checkbox" required>Saya paham seluruh data buku saat ini akan dihapus permanen.</label><div data-error></div>${dialogActions('Hapus & mulai dari nol')}</form>`);if(action==='edit-book')bookModal(row);if(action==='stock-in')stockModal(row);if(action==='stock-loss')stockModal(row,true);
  if(action==='new-rombel')rombelModal();if(action==='edit-rombel')rombelModal(row);if(action==='label')await busy(b,'Membuat…',()=>labelModal(row));
  if(action==='new-user')userModal();if(action==='edit-user')userModal(row);if(action==='reset-user')userModal(row,true);
  if(action==='close-modal')closeModal();if(action==='change-password')passwordModal();
  if(action==='health')await busy(b,'Memeriksa…',async()=>{const r=await api('health');$('#health-result').innerHTML=`<div class="success-box">Database terhubung · Schema ${esc(r.schema_version)} · Respons perangkat ${number(S.lastLatency)} ms</div>`;});
  if(action==='next-page'){if(['history','audit'].includes(S.view)){S.cursors.push(S.cursor);S.cursor=S.rows.at(-1);}else S.offset+=S.limit;awaitView();}
  if(action==='prev-page'){if(['history','audit'].includes(S.view))S.cursor=S.cursors.pop()||null;else S.offset=Math.max(0,S.offset-S.limit);awaitView();}
  if(action==='review-books'){navigate('books');setTimeout(()=>{S.review=true;awaitView(true);},30);}
  if(action==='add-item'){if(S.items.length>=30)throw new Error('Maksimum 30 baris.');S.items.push({buku_id:'',jumlah:1,kondisi:'baik'});renderItems();}
  if(action==='remove-item'){S.items.splice(Number(b.dataset.index),1);renderItems();}
  if(action==='cancel-tx'){S.scan=null;S.items=[];renderTransaction();}
  if(action==='new-tx'){S.receipt=null;renderReceipt();$('#barcode-input').value='';$('#barcode-input').focus();}
  if(action==='history-receipt')showModal('Bukti transaksi','Identitas dan rincian saat pencatatan.',receiptHTML(row,true));
  if(action==='print-receipt'||action==='print-modal'){document.body.classList.add(action==='print-modal'?'printing-modal':'printing');window.print();document.body.classList.remove('printing','printing-modal');}
  if(action==='download-qr')downloadFile(S.qr,`SINABOS-${S.qrName}.svg`,'image/svg+xml');
  if(action==='download-report')exportReport();
  if(action==='camera-open')await startCamera();if(action==='camera-close')stopCamera();
  if(action==='pending-check')await checkPending(b);if(action==='pending-retry')await retryPending(b);
 }catch(e){toast(e.message,'error');}
});
async function boot(){try{localStorage.removeItem('ADMIN_SESSION');}catch{}const demo=$('meta[name="sinabos-demo"]')?.content==='true';if(demo){$('#demo-banner').hidden=false;$('#demo-accounts').hidden=false;$('#demo-accounts').innerHTML='<strong>Akun demo lokal — bukan akun sekolah</strong><br>Admin: <code>admin</code> / <code>Demo-Admin-2026!</code><br>Guru: <code>guru.demo</code> / <code>Demo-Guru-2026!</code>';}
 try{const r=await api('me',{}, {read:true});await enter(r.user);}catch(e){showLogin();if(e.status!==401)errorBox($('#login-form'),e);}}
boot();
